import type { Metadata } from "next";
import "../styles/globals.css";
import SessionProviderWrapper from "@/components/ProviderComponent/SessionProvider";

export const metadata: Metadata = {
  title: "Black Angel Store",
  description: "Generated by create next app",
  icons: {
    icon: "/img/blackangel_icon.jpg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body className="antialiased">
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
